import Link from 'next/link';
import { AlertTriangle, CheckCircle, AlertCircle, Download, MessageSquare, Scale } from 'lucide-react';

export interface AiAnalysis {
  riskLevel: 'safe' | 'caution' | 'danger';
  score: number;
  redFlags: string[];
  greenFlags: string[];
  recommendation: string;
  nextSteps: string[];
}

interface FraudReportProps {
  aiAnalysis: AiAnalysis;
  userDescription: string;
  propertyType: string;
}

const riskConfig = {
  safe: {
    label: '✅ LOOKS SAFE',
    bg: 'bg-green-900/40',
    border: 'border-green-500',
    text: 'text-green-300',
    scoreColor: '#22c55e',
  },
  caution: {
    label: '⚠️ PROCEED WITH CAUTION',
    bg: 'bg-yellow-900/30',
    border: 'border-yellow-500',
    text: 'text-yellow-300',
    scoreColor: '#eab308',
  },
  danger: {
    label: '🚨 HIGH RISK — DO NOT PAY',
    bg: 'bg-red-900/40',
    border: 'border-red-500',
    text: 'text-red-300',
    scoreColor: '#ef4444',
  },
};

function CircleScore({ score, color }: { score: number; color: string }) {
  const radius = 36;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;

  return (
    <div className="relative w-24 h-24 mx-auto">
      <svg className="w-24 h-24 -rotate-90" viewBox="0 0 96 96">
        <circle cx="48" cy="48" r={radius} stroke="#1e3a5f" strokeWidth="8" fill="none" />
        <circle
          cx="48"
          cy="48"
          r={radius}
          stroke={color}
          strokeWidth="8"
          fill="none"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          style={{ transition: 'stroke-dashoffset 1s ease' }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-2xl font-extrabold text-white leading-none">{score}</span>
        <span className="text-[10px] text-gray-500 mt-0.5">/ 100</span>
      </div>
    </div>
  );
}

function downloadReport(analysis: AiAnalysis, description: string, propertyType: string) {
  const lines = [
    'UloFind — Ada Fraud Detection Report',
    '=====================================',
    `Risk Level: ${analysis.riskLevel.toUpperCase()}`,
    `Safety Score: ${analysis.score}/100`,
    `Property Type: ${propertyType}`,
    '',
    'DESCRIPTION PROVIDED:',
    description,
    '',
    `RED FLAGS (${analysis.redFlags.length}):`,
    ...analysis.redFlags.map((f) => `  ⚠ ${f}`),
    '',
    `GREEN FLAGS (${analysis.greenFlags.length}):`,
    ...analysis.greenFlags.map((f) => `  ✓ ${f}`),
    '',
    "ADA'S RECOMMENDATION:",
    analysis.recommendation,
    '',
    'NEXT STEPS:',
    ...analysis.nextSteps.map((s, i) => `  ${i + 1}. ${s}`),
    '',
    `Generated by UloFind Ada AI — ${new Date().toLocaleString()}`,
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ada-fraud-report-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function FraudReport({ aiAnalysis, userDescription, propertyType }: FraudReportProps) {
  const cfg = riskConfig[aiAnalysis.riskLevel];
  const waText = encodeURIComponent(
    `Ada Fraud Check Result for a ${propertyType}:\n` +
    `Risk Level: ${aiAnalysis.riskLevel.toUpperCase()}\n` +
    `Safety Score: ${aiAnalysis.score}/100\n\n` +
    `Recommendation: ${aiAnalysis.recommendation}\n\n` +
    `Checked via UloFind — https://ulofind.fintigen.com/verify`
  );

  return (
    <div className="space-y-5 animate-in fade-in duration-500">
      {/* ── Risk badge ── */}
      <div className={`rounded-2xl border-2 p-6 text-center ${cfg.bg} ${cfg.border}`}>
        <p className={`text-2xl font-extrabold tracking-wide ${cfg.text}`}>{cfg.label}</p>
        <div className="mt-4">
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-3">Safety Score</p>
          <CircleScore score={aiAnalysis.score} color={cfg.scoreColor} />
          <p className="text-xs text-gray-500 mt-3">
            {aiAnalysis.score >= 70
              ? 'Low fraud probability'
              : aiAnalysis.score >= 40
              ? 'Moderate fraud probability — verify before paying'
              : 'High fraud probability — exercise extreme caution'}
          </p>
        </div>
      </div>

      {/* ── Red flags ── */}
      {aiAnalysis.redFlags.length > 0 && (
        <div>
          <h3 className="text-red-400 font-bold text-sm uppercase tracking-widest mb-3 flex items-center gap-2">
            <AlertTriangle size={14} /> Red Flags ({aiAnalysis.redFlags.length})
          </h3>
          <div className="space-y-2">
            {aiAnalysis.redFlags.map((flag, i) => (
              <div key={i} className="flex gap-3 bg-red-900/30 border border-red-800/60 rounded-xl px-4 py-3">
                <AlertCircle size={16} className="text-red-400 mt-0.5 flex-shrink-0" />
                <p className="text-red-200 text-sm leading-relaxed">{flag}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Green flags ── */}
      {aiAnalysis.greenFlags.length > 0 && (
        <div>
          <h3 className="text-green-400 font-bold text-sm uppercase tracking-widest mb-3 flex items-center gap-2">
            <CheckCircle size={14} /> Green Flags ({aiAnalysis.greenFlags.length})
          </h3>
          <div className="space-y-2">
            {aiAnalysis.greenFlags.map((flag, i) => (
              <div key={i} className="flex gap-3 bg-green-900/30 border border-green-800/60 rounded-xl px-4 py-3">
                <CheckCircle size={16} className="text-green-400 mt-0.5 flex-shrink-0" />
                <p className="text-green-200 text-sm leading-relaxed">{flag}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Ada's recommendation ── */}
      <div className="border border-gray-700 rounded-2xl p-5" style={{ backgroundColor: '#0d1f3c' }}>
        <p className="text-xs text-gray-500 uppercase tracking-widest mb-3 flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse inline-block" />
          Ada's Recommendation
        </p>
        <p className="text-gray-200 text-sm leading-relaxed">{aiAnalysis.recommendation}</p>
      </div>

      {/* ── Next steps ── */}
      <div>
        <h3 className="text-gray-400 font-bold text-sm uppercase tracking-widest mb-3">
          Next Steps
        </h3>
        <ol className="space-y-3">
          {aiAnalysis.nextSteps.map((step, i) => (
            <li key={i} className="flex gap-3">
              <span
                className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5"
                style={{ backgroundColor: '#0f5132', color: '#fff' }}
              >
                {i + 1}
              </span>
              <p className="text-gray-300 text-sm leading-relaxed">{step}</p>
            </li>
          ))}
        </ol>
      </div>

      {/* ── Bottom CTAs ── */}
      <div className="border-t border-gray-800 pt-5 grid gap-3">
        <button
          onClick={() => downloadReport(aiAnalysis, userDescription, propertyType)}
          className="flex items-center justify-center gap-2 border border-gray-700 text-gray-300 py-3 rounded-xl font-medium text-sm hover:bg-white/5 transition-colors"
        >
          <Download size={16} />
          Save this report
        </button>
        <a
          href={`https://wa.me/?text=${waText}`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white py-3 rounded-xl font-semibold text-sm transition-colors"
        >
          <MessageSquare size={16} />
          Share via WhatsApp
        </a>
        <Link
          href="#lawyer-referral"
          className="flex items-center justify-center gap-2 border border-gray-700 text-gray-400 py-3 rounded-xl font-medium text-sm hover:bg-white/5 transition-colors"
        >
          <Scale size={16} />
          Talk to a Nsukka lawyer
        </Link>
      </div>
    </div>
  );
}
